# Generated by Django 5.2.13 on 2026-04-25 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=24, unique=True)),
                ('tracking_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('corruption_type', models.CharField(choices=[('bribery', 'Bribery'), ('embezzlement', 'Embezzlement'), ('abuse-of-power', 'Abuse of power'), ('procurement', 'Procurement'), ('extortion', 'Extortion'), ('other', 'Other')], max_length=32)),
                ('description', models.TextField()),
                ('incident_date', models.DateField()),
                ('region_id', models.CharField(max_length=64)),
                ('city_id', models.CharField(max_length=64)),
                ('organization_type_id', models.CharField(max_length=64)),
                ('organization_id', models.CharField(max_length=128)),
                ('contact', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('done', 'Done')], db_index=True, default='pending', max_length=16)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('ai_risk_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ai_flags', models.JSONField(blank=True, default=list)),
                ('ai_source', models.CharField(blank=True, default='', max_length=24)),
            ],
            options={
                'db_table': 'reports',
                'indexes': [models.Index(fields=['status', 'created_at'], name='reports_status_19e159_idx'), models.Index(fields=['region_id', 'status'], name='reports_region__aa0775_idx'), models.Index(fields=['tracking_id'], name='reports_trackin_82da4f_idx'), models.Index(fields=['public_id'], name='reports_public__8e0d9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='reports/evidence/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='reports.report')),
            ],
            options={
                'db_table': 'report_evidences',
                'indexes': [models.Index(fields=['report', 'created_at'], name='report_evid_report__91a7a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('done', 'Done')], max_length=16)),
                ('title_key', models.CharField(max_length=120)),
                ('description_key', models.CharField(max_length=120)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='reports.report')),
            ],
            options={
                'db_table': 'report_timelines',
                'indexes': [models.Index(fields=['report', 'created_at'], name='report_time_report__ca3057_idx')],
            },
        ),
    ]
