# Generated by Django 5.2.13 on 2026-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reward_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reward amount in USDT assigned by admin when status → done', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reward_claimed',
            field=models.BooleanField(default=False, help_text='True once the whistleblower has claimed the payout'),
        ),
        migrations.AddField(
            model_name='report',
            name='reward_claimed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the reward was claimed', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reward_tx_hash',
            field=models.CharField(blank=True, default='', help_text='On-chain tx hash (or mock reference) for audit trail', max_length=128),
        ),
        migrations.AddField(
            model_name='report',
            name='reward_wallet',
            field=models.CharField(blank=True, default='', help_text='Crypto wallet address supplied at claim time', max_length=255),
        ),
    ]
